spring:
  datasource: 
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    thymeleaf:
      cache: false
  email:
    sender: ${EMAIL_SENDER}
    password: ${EMAIL_PASSWORD}
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  logging:
    level:
      org.springframework.security: DEBUG


