spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oo2_grupo13
    username: root
    password: toto30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    cache: false
  email:
    sender: morenarioscarnevale5@gmail.com
    password: Toto301004
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
